version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "5001:5001"
    depends_on:
      - ocr
      - ai
    restart: always
  ai:
    build: ./ai-service
    ports:
      - "4000:4000"
    restart: always
  ocr:
    build: ./ocr-service
    ports:
      - "5000:5000"
    restart: always
